### ISSUE TITLE
[suggestion] Documentation should state folder is relative to /home/node/

### ISSUE THREAD

**Issue by nmwael** [intel/SGX-TDX-DCAP-QuoteVerificationService#3]
When reading:
https://github.com/intel/SGX-TDX-DCAP-QuoteVerificationService/tree/stable?tab=readme-ov-file#general-service-configuration

one gets the idea that QVS_CA_CERT_DIRECTORIES or QVS_SERVICE_CERT_FILE etc, could be place anywhere, however when booting up the system this is clearly not the case:

 Error: Loading link which directs outside of provided locations: ["/home/node/"] is forbidden!                        │
│     at readFileSafely (/QVS/src/common/readFileSafely.js:68:23)                                                       │
│     at /QVS/src/common/RestClient.js:65:73

**Comment by b-garbacz** [comment]
If you want to use a symlink, it should point to a file located in an allowed directory, such as `/home/node`. You received an error indicating that symlinked files outside the permitted directory cannot be read. You can check it out [here](https://github.com/intel/SGX-TDX-DCAP-QuoteVerificationService/blob/541531b838d17f7418f7d86c16974f98f2fa81b4/src/common/readFileSafely.js#L57).
 
You can add your own path to the array if you are sure that it will be safe and no one will modify your files.
