### ISSUE TITLE
[suggestion] describe that root ca must be added

### ISSUE THREAD

**Issue by nmwael** [intel/SGX-TDX-DCAP-QuoteVerificationService#5]
Both PCS and CRL are unable to run unless you add root ca for https://certificates.trustedservices.intel.com/
To
- QVS_PCS_CLIENT_CA_CERT_DIRECTORIES
- QVS_CRL_CLIENT_CA_CERT_DIRECTORIES

**Comment by nmwael** [comment]
@pblajer I cannot see [this](https://certificates.trustedservices.intel.com/) is handled in your commits?

**Comment by b-garbacz** [comment]
Hey @nmwael 
A self-signed CA certificate for SSL connection is currently missing and needs to be included in the `internal_ca` directory. You can download the required file for now from this [link](https://comodoca.my.salesforce.com/sfc/p/#1N000002Ljih/a/3l000000VZ4M/ie5Sho19m8SLjTZkH_VL8efOD1qyGFt9h5Ju1ddtbKQ), and it will be added to QVS in one next releases.

**Comment by nmwael** [comment]
I know and I've done so :) anyway thanks for mentioning it.. and looking forward to the next release.

**Comment by bsulich2** [comment]
Fixed in https://github.com/intel/SGX-TDX-DCAP-QuoteVerificationService/pull/11.
